/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ulpgc.twitterrdf;

import static es.ulpgc.twitterrdf.MainUtilities.getFormattedTweets;
import static es.ulpgc.twitterrdf.MainUtilities.getTweets;
import static es.ulpgc.twitterrdf.MainUtilities.writeToFile;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import twitter4j.Status;

/**
 *
 * @author dadepe
 */
public class TwitterRDFGUI extends javax.swing.JFrame {

    /**
     * Creates new form TwitterRDFGUI
     */
    File fileToWrite;
    RDFHandler rdfHandler;
    List<Status> tweets = null;
    String subject = "";
    String term = "";
    public TwitterRDFGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        output_selector = new javax.swing.ButtonGroup();
        path_chooser = new javax.swing.JFileChooser();
        ntweetspinner = new javax.swing.JSpinner();
        nTweetsLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        xml_rdfbutton = new javax.swing.JRadioButton();
        turtlebutton = new javax.swing.JRadioButton();
        busq_label = new javax.swing.JLabel();
        search_term_field = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_tweets_TP = new javax.swing.JTextPane();
        save_button = new javax.swing.JButton();
        fromatLabel = new javax.swing.JLabel();
        fileChooserButton = new javax.swing.JButton();
        rutaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        subjectTF = new javax.swing.JTextField();

        path_chooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));

        ntweetspinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));

        nTweetsLabel.setText("nº de Tweets");

        logo.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_alt.png"))); // NOI18N
        logo.setText("TwitterRDF");

        output_selector.add(xml_rdfbutton);
        xml_rdfbutton.setSelected(true);
        xml_rdfbutton.setText("XML/RDF");
        xml_rdfbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xml_rdfbuttonActionPerformed(evt);
            }
        });

        output_selector.add(turtlebutton);
        turtlebutton.setText("Turtle");

        busq_label.setText("Término de Búsqueda");

        search_term_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_term_fieldFocusGained(evt);
            }
        });
        search_term_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_term_fieldActionPerformed(evt);
            }
        });

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        show_tweets_TP.setEditable(false);
        jScrollPane1.setViewportView(show_tweets_TP);

        save_button.setText("Guardar");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        fromatLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        fromatLabel.setText("Formato");

        fileChooserButton.setText("Seleccionar ruta");
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });

        rutaLabel.setText("No se ha seleccionado");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Ruta");

        subjectLabel.setText("Tema de Búsqueda");

        subjectTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(logo)
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(subjectTF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(search_term_field, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subjectLabel)
                                    .addComponent(nTweetsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ntweetspinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(busq_label))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(38, 38, 38)))
                .addGap(18, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(fromatLabel)
                            .addGap(142, 142, 142))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fileChooserButton)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(turtlebutton)
                                    .addComponent(xml_rdfbutton)))
                            .addGap(70, 70, 70))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rutaLabel)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save_button)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busq_label)
                    .addComponent(subjectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rutaLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_term_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nTweetsLabel)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ntweetspinner))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileChooserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xml_rdfbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(turtlebutton)
                        .addGap(18, 18, 18)
                        .addComponent(save_button)
                        .addGap(59, 59, 59))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xml_rdfbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xml_rdfbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xml_rdfbuttonActionPerformed

    private void search_term_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_term_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_term_fieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String search_term = search_term_field.getText();
        try {
            ntweetspinner.commitEdit();
        } catch ( java.text.ParseException e ) {
            JOptionPane.showMessageDialog(this, "Eggs are not supposed to be green.");
        }
        int n_tweets = (Integer) ntweetspinner.getValue();
        
        tweets = getTweets(search_term, n_tweets);
        
        show_tweets_TP.setText(getFormattedTweets(tweets));
        term = search_term;
        subject = subjectTF.getText();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void search_term_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_term_fieldFocusGained

    }//GEN-LAST:event_search_term_fieldFocusGained

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        String format = "";
        if(tweets == null){
            JOptionPane.showMessageDialog(this, "Debes realizar una busqueda primero.");
        } else {            
            String path = rutaLabel.getText();
            if ("No se ha seleccionado".equals(path)){
                JOptionPane.showMessageDialog(this, "Selecciona donde guardar el resultado.");
            } else {
                rdfHandler = new RDFHandler(tweets, subject, term);
                rdfHandler.generateTweetResources();
                if (xml_rdfbutton.isSelected()){
                    format = "XML/RDF";
                } else if(turtlebutton.isSelected()){
                    format = "Turtle";
                }
                boolean doneWrite = writeToFile(fileToWrite, rdfHandler.getModel(), format);
                if(doneWrite){
                    JOptionPane.showMessageDialog(this, "Se ha guardado correctamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Ha habido un error al guardar el archivo.");
                }
            }      
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        path_chooser.showSaveDialog(null);
        fileToWrite = path_chooser.getSelectedFile();
        String path = fileToWrite.getAbsolutePath();
        rutaLabel.setText(path);
    }//GEN-LAST:event_fileChooserButtonActionPerformed

    private void subjectTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitterRDFGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitterRDFGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitterRDFGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitterRDFGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwitterRDFGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busq_label;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JLabel fromatLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nTweetsLabel;
    private javax.swing.JSpinner ntweetspinner;
    private javax.swing.ButtonGroup output_selector;
    private javax.swing.JFileChooser path_chooser;
    private javax.swing.JLabel rutaLabel;
    private javax.swing.JButton save_button;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField search_term_field;
    private javax.swing.JTextPane show_tweets_TP;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextField subjectTF;
    private javax.swing.JRadioButton turtlebutton;
    private javax.swing.JRadioButton xml_rdfbutton;
    // End of variables declaration//GEN-END:variables
}
