/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ulpgc.twitterrdf;

import static es.ulpgc.twitterrdf.Main.getFormattedTweets;
import static es.ulpgc.twitterrdf.TwitterHandler.searchTweets;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import twitter4j.Status;
import twitter4j.TwitterException;

/**
 *
 * @author dadepe
 */
public class TwitterRDFGUI extends javax.swing.JFrame {

    /**
     * Creates new form TwitterRDFGUI
     */
    public TwitterRDFGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        output_selector = new javax.swing.ButtonGroup();
        path_chooser = new javax.swing.JFileChooser();
        ntweetspinner = new javax.swing.JSpinner();
        nTweetsLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        xml_rdfbutton = new javax.swing.JRadioButton();
        turtlebutton = new javax.swing.JRadioButton();
        busq_label = new javax.swing.JLabel();
        search_term_field = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_tweets_TP = new javax.swing.JTextPane();
        save_button = new javax.swing.JButton();
        fromatLabel = new javax.swing.JLabel();
        fileChooserButton = new javax.swing.JButton();
        rutaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        path_chooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));

        ntweetspinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));

        nTweetsLabel.setText("nº de Tweets");

        logo.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_alt.png"))); // NOI18N
        logo.setText("TwitterRDF");

        output_selector.add(xml_rdfbutton);
        xml_rdfbutton.setSelected(true);
        xml_rdfbutton.setText("XML/RDF");
        xml_rdfbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xml_rdfbuttonActionPerformed(evt);
            }
        });

        output_selector.add(turtlebutton);
        turtlebutton.setText("Turtle");

        busq_label.setText("Término de Búsqueda");

        search_term_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_term_fieldFocusGained(evt);
            }
        });
        search_term_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_term_fieldActionPerformed(evt);
            }
        });

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        show_tweets_TP.setEditable(false);
        jScrollPane1.setViewportView(show_tweets_TP);

        save_button.setText("Guardar");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        fromatLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        fromatLabel.setText("Formato");

        fileChooserButton.setText("Seleccionar ruta");
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });

        rutaLabel.setText("No se ha seleccionado");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Ruta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(logo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(search_term_field, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ntweetspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(searchButton)
                                    .addComponent(busq_label))
                                .addGap(18, 18, 18)
                                .addComponent(nTweetsLabel)))
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addContainerGap(168, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(save_button)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fromatLabel)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fileChooserButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(turtlebutton)
                                .addComponent(xml_rdfbutton)))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rutaLabel)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(logo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(busq_label)
                            .addComponent(nTweetsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_term_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ntweetspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rutaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileChooserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xml_rdfbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(turtlebutton)
                        .addGap(18, 18, 18)
                        .addComponent(save_button)
                        .addGap(59, 59, 59))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xml_rdfbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xml_rdfbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xml_rdfbuttonActionPerformed

    private void search_term_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_term_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_term_fieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String search_term = search_term_field.getText();
        try {
            ntweetspinner.commitEdit();
        } catch ( java.text.ParseException e ) {
            JOptionPane.showMessageDialog(this, "Eggs are not supposed to be green.");
        }
        int n_tweets = (Integer) ntweetspinner.getValue();
        
        
        show_tweets_TP.setText(getFormattedTweets(search_term, n_tweets));
    }//GEN-LAST:event_searchButtonActionPerformed

    private void search_term_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_term_fieldFocusGained

    }//GEN-LAST:event_search_term_fieldFocusGained

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        
    }//GEN-LAST:event_save_buttonActionPerformed

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        path_chooser.showSaveDialog(null);
        File f = path_chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        rutaLabel.setText(path);
    }//GEN-LAST:event_fileChooserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitterRDFGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitterRDFGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitterRDFGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitterRDFGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwitterRDFGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busq_label;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JLabel fromatLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nTweetsLabel;
    private javax.swing.JSpinner ntweetspinner;
    private javax.swing.ButtonGroup output_selector;
    private javax.swing.JFileChooser path_chooser;
    private javax.swing.JLabel rutaLabel;
    private javax.swing.JButton save_button;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField search_term_field;
    private javax.swing.JTextPane show_tweets_TP;
    private javax.swing.JRadioButton turtlebutton;
    private javax.swing.JRadioButton xml_rdfbutton;
    // End of variables declaration//GEN-END:variables
}
